import React from 'react';

interface CheatSheetProps {
    content: string | null;
    isGenerating: boolean;
}

export const CheatSheet: React.FC<CheatSheetProps> = ({ content, isGenerating }) => {
    return (
        <div className="w-full lg:w-2/3 h-full animate-slide-left">
            <div className="bg-[#fdfbf7] text-slate-800 rounded-xl shadow-2xl min-h-[70vh] max-h-[85vh] overflow-y-auto relative flex flex-col paper-texture">
                {/* Paper Lines Pattern */}
                <div className="absolute inset-0 pointer-events-none opacity-10" 
                     style={{ backgroundImage: 'linear-gradient(#000000 1px, transparent 1px)', backgroundSize: '100% 2rem', marginTop: '3rem' }}>
                </div>
                
                {/* Header */}
                <div className="sticky top-0 bg-[#fdfbf7] z-10 px-8 py-6 border-b-2 border-slate-200">
                    <div className="flex justify-between items-end">
                        <div>
                            <h1 className="text-4xl font-black text-slate-900 uppercase tracking-tight">Cheat Sheet</h1>
                            <p className="text-slate-500 font-serif italic text-sm mt-1">Tổng hợp kiến thức trọng tâm • {new Date().toLocaleDateString()}</p>
                        </div>
                        <div className="w-16 h-16 border-4 border-double border-red-800 rounded-full flex items-center justify-center opacity-20 transform rotate-12">
                            <span className="text-[10px] font-black text-red-900 uppercase">Top Secret</span>
                        </div>
                    </div>
                </div>

                {/* Content */}
                <div className="flex-1 p-8 md:p-12 relative">
                    {content ? (
                        <article className="prose prose-slate max-w-none prose-headings:font-bold prose-h1:text-2xl prose-h2:text-xl prose-p:leading-relaxed font-serif">
                            <div className="whitespace-pre-wrap">{content}</div>
                        </article>
                    ) : (
                        <div className="h-full flex flex-col items-center justify-center text-slate-400 opacity-50 gap-4 min-h-[400px]">
                            {isGenerating ? (
                                <>
                                    <span className="material-symbols-outlined text-6xl animate-spin text-amber-500">settings</span>
                                    <p className="font-bold">Đang in ấn tài liệu...</p>
                                </>
                            ) : (
                                <>
                                    <span className="material-symbols-outlined text-8xl">description</span>
                                    <p className="text-lg font-medium">Chưa có dữ liệu. Nhấn "Tạo Cheat Sheet" để bắt đầu.</p>
                                </>
                            )}
                        </div>
                    )}
                </div>
                
                {/* Footer */}
                <div className="p-4 border-t border-slate-200 text-center text-xs text-slate-400 font-mono">
                    GENERATED BY LEARNAI • GEMINI 3 PRO ENGINE
                </div>
            </div>
        </div>
    );
};